### ISSUE TITLE
Улучшения тестов

### ISSUE THREAD

**Issue by mglukhikh** [LLDay/BigDouble#7]
1. import Test annotation. Не нужно без необходимости использовать полные имена.
2. Для проверки, что тест бросает исключение, существуют стандартные механизмы. См. здесь: https://stackoverflow.com/questions/40268446/junit-5-how-to-assert-an-exception-is-thrown.

**Comment by LLDay** [comment]
@mglukhikh, не получается использовать сокращенное имя аннотации

**Comment by mglukhikh** [comment]
Почему не получается?

**Comment by LLDay** [comment]
@mglukhikh, из-за коллизии имен аннотации и тестового класса
